### ISSUE TITLE
Trash should be optional

### ISSUE THREAD

**Issue by Crlax22** [billziss-gh/EnergyBar#3]
The Trash cann should be optional. Id rather have a skip button next to the play pause than the trash.

Also if you tap on the now playing it should open that app

**Comment by PowerMike252** [comment]
Emptying the trash with a long press would be nice.

**Comment by billziss-gh** [comment]
@Crlax22 

- Latest source makes the trash icon optional (no binary yet).
- There is no skip button, but you can long press on the play/pause button to get the same functionality.
- You can long press the Now Playing widget to open the current media player.

@PowerMike252 

I thought about this but what happens when someone has disabled the Trash warning in the Finder? Someone could inadvertently long press the Trash button and all files would be gone.

**Comment by billziss-gh** [comment]
@PowerMike252 EnergyBar now supports folders on the right side of the separator similar to the system Dock. The folders are opened inside the Touch Bar by default. The trash folder includes an Empty button to empty the trash without opening Finder.

**Comment by billziss-gh** [comment]
EnergyBar v1.2 is out and includes multiple improvements.

https://github.com/billziss-gh/EnergyBar/releases
